import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'sr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'sr';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

const translations: Record<Language, Record<string, string>> = {
  sr: {
    'nav.home': 'Početna',
    'nav.services': 'Usluge',
    'nav.contact': 'Kontakt',
    'hero.heading': 'Papirna Galanterija',
    'hero.tagline': 'Lako do higijene uz Lako Sistem',
    'hero.cta': 'Zatražite Ponudu',
    'about.title': 'O nama',
    'about.text1': 'Lako Sistem je vodeća kompanija u oblasti papirne galanterije i profesionalne hemije za hotele i ugostiteljske objekte. Sa dugogodišnjim iskustvom, posvećeni smo pružanju vrhunskih proizvoda i usluga.',
    'about.text2': 'Naš slogan "Lako do Higijene sa Lako Sistemom" odražava našu misiju - da održavanje higijene učinimo jednostavnim i efikasnim za sve naše klijente.',
    'about.card1.title': 'Dugogodišnje Iskustvo',
    'about.card1.desc': 'Pouzdani partner u oblasti higijene i galanterije',
    'about.card2.title': 'Vrhunski Proizvodi',
    'about.card2.desc': 'Najviši standardi kvaliteta za vaše potrebe',
    'about.card3.title': 'Brza Isporuka',
    'about.card3.desc': 'Efikasna logistika širom Srbije',
    'features.heading': 'Zašto Odabrati Lako Sistem?',
    'features.subheading': 'Sa dugogodišnjim iskustvom u branši, pružamo vrhunske proizvode i usluge koje zadovoljavaju najviše standarde kvaliteta.',
    'features.feature1': 'Visok kvalitet proizvoda',
    'features.feature2': 'Konkurentne cene',
    'features.feature3': 'Brza dostava',
    'features.feature4': 'Profesionalna podrška',
    'features.feature5': 'Veliki izbor proizvoda',
    'features.feature6': 'Dugogodišnje iskustvo',
    'features.cta.title': 'Zatražite Ponudu',
    'features.cta.desc': 'Kontaktirajte nas danas i dobijte personalizovanu ponudu prilagođenu vašim potrebama.',
    'features.cta.button': 'Kontaktirajte Nas',
    'features.quality.title': 'Vrhunski kvalitet',
    'features.quality.desc': 'Sarađujemo samo sa renomiranim proizvođačima',
    'features.delivery.title': 'Brza dostava',
    'features.delivery.desc': 'Pouzdana dostava širom Srbije',
    'features.support.title': 'Podrška 24/7',
    'features.support.desc': 'Uvek tu za vas kada nam zatrebate',
    'features.price.title': 'Konkurentne cene',
    'features.price.desc': 'Najbolji odnos cene i kvaliteta',
    'services.title': 'Naše Usluge',
    'services.subtitle': 'Kompletan asortiman proizvoda i usluga za održavanje higijene u vašem prostoru',
    'services.paper.title': 'Papirna Galanterija',
    'services.paper.desc': 'Širok asortiman papirnih proizvoda za sve vaše potrebe - toalet papir, ubrus, salvete i još mnogo toga.',
    'services.paper.button': 'Saznaj više',
    'services.paper.item1': 'Toaletni papir premium kvaliteta',
    'services.paper.item2': 'Ubrusi i salvete raznih dimenzija',
    'services.paper.item3': 'Kuhinjske rolne i papirnati ručnici',
    'services.paper.item4': 'Specijalizam proizvodi za hotele',
    'services.chemistry.title': 'Hemija za Hotele',
    'services.chemistry.desc': 'Profesionalna hemija za čišćenje i održavanje hotela, restorana i poslovnih prostora.',
    'services.chemistry.button': 'Saznaj više',
    'services.chemistry.item1': 'Deterđenti i sredstva za pranje',
    'services.chemistry.item2': 'Dezinfekciona sredstva',
    'services.chemistry.item3': 'Sredstva za čišćenje kuhinja',
    'services.transport.title': 'Prevoz i Dostava',
    'services.transport.desc': 'Brza i pouzdana dostava vaših porudžbina direktno na vašu adresu.',
    'services.transport.button': 'Saznaj više',
    'contact.title': 'Kontaktirajte nas',
    'contact.subtitle': 'Spremni smo da odgovorimo na sva vaša pitanja i pomoćemo vam sa vašim potrebama',
    'contact.name': 'Ime i prezime',
    'contact.email': 'Email',
    'contact.phone': 'Telefon',
    'contact.message': 'Poruka',
    'contact.send': 'Pošalji poruku',
    'contact.sending': 'Šaljem...',
    'contact.success': 'Poruka uspešno poslata!',
    'contact.error': 'Greška pri slanju poruke. Molimo pokušajte ponovo.',
    'contact.form.title': 'Pošaljite nam poruku',
    'contact.info.title': 'Kontakt Informacije',
    'contact.info.phone.label': 'Telefon',
    'contact.info.phone.note': 'Uvek dostupni',
    'contact.info.email.label': 'Email',
    'contact.info.email.note': 'Odgovaramo u roku 24h',
    'contact.info.address.label': 'Adresa',
    'contact.info.address.note': 'Poseta isključivo uz najavu',
    'contact.info.address': 'Bulevar Oslobodjenja 133a/3, 11000 Beograd',
    'contact.info.phone': '+381 60 66 77 009',
    'contact.info.email': 'lakosistem@aislike.rs',
    'footer.quick_links': 'Brzi Linkovi',
    'footer.contact_info': 'Kontakt Informacije',
    'footer.tagline': 'Lako do Higijene sa Lako Sistemom',
    'footer.description': 'Vaš pouzdan partner za profesionalne higijenske proizvode i usluge.',
    'footer.rights': '© 2024 Lako Sistem. Sva prava zadržana.',
    'services.page.title': 'Naše Usluge i Transport',
    'services.page.subtitle': 'Papirna galanterija i profesionalna hemijska sredstva za čišćenje u velikim količinama, uz prevoz i transport do vaših vrata',
    'services.page.paper.title': 'Papirna Galanterija',
    'services.page.paper.desc': 'Nudimo kompletan asortiman papirne galanterije za hotele, restorane i ugostiteljske objekte. Naši proizvodi odlikuju se visokim kvalitetom i pristupačnim cenama.',
    'services.page.paper.why': 'Zašto Izabrati Nas',
    'services.page.chemistry.references': 'Naše Reference',
    'services.page.chemistry.ref_text1': 'Sarađujemo sa vodećim hotelskim lancima, restoranima i poslovnim objektima u regionu. Naši klijenti prepoznaju kvalitet našeg programa i pouzdanost u isporuci. Bilo da vodite boutique hotel, veliku hotelsku kuću ili lanac restorana, imamo rešenje za vas.',
    'services.page.chemistry.ref_text2': 'Svi proizvodi su testirani i odobreni od strane relevantnih institucija, garantujući vam maksimalne standarde higijene i sigurnosti za vaše goste i zaposlene.',
    'services.page.paper.products': 'Naši proizvodi:',
    'services.page.paper.p1': 'Toaletni papir (1-4 sloja)',
    'services.page.paper.p2': 'Ubrusi i salvete različitih dimenzija',
    'services.page.paper.p3': 'Kuhinjske rolne',
    'services.page.paper.p4': 'Papirnati ručnici',
    'services.page.paper.p5': 'Industrijske rolne',
    'services.page.chemistry.title': 'Profesionalna Hemija',
    'services.page.chemistry.desc': 'Profesionalna hemijska sredstva za čišćenje koja garantuju najviše standarde higijene. Sva sredstva su sertifikovana i bezbedna za upotrebu.',
    'services.page.chemistry.products': 'Naša ponuda:',
    'services.page.chemistry.p1': 'Deterđenti i omekšivači',
    'services.page.chemistry.p2': 'Dezinfekciona sredstva',
    'services.page.chemistry.p3': 'Sredstva za čišćenje stakla',
    'services.page.chemistry.p4': 'Sredstva za čišćenje kuhinja',
    'services.page.chemistry.p5': 'Sredstva za čišćenje sanitarija',
    'services.page.chemistry.p6': 'Sredstva za čišćenje podova',
    'services.page.transport.title': 'Transport i Dostava',
    'services.page.transport.desc': 'Obezbeđujemo brzu i pouzdanu dostavu širom Srbije. Naš vozni park omogućava transport proizvoda u optimalnim uslovima.',
    'services.page.transport.features': 'Prednosti našeg transporta:',
    'services.page.transport.f1': 'Besplatna dostava za narudžbine preko određene vrednosti',
    'services.page.transport.f2': 'Fleksibilni termini isporuke',
    'services.page.transport.f3': 'Profesionalni vozači',
    'services.page.transport.f4': 'Praćenje pošiljke u realnom vremenu',
    'services.page.transport.f5': 'Sigurna i brza dostava',
    'services.page.transport.card1.title': 'Brza Dostava',
    'services.page.transport.card1.desc': 'Isporuka u roku od 24-48h na teritoriji cele Srbije',
    'services.page.transport.card2.title': 'Sigurno Pakovanje',
    'services.page.transport.card2.desc': 'Proizvodi pažljivo upakovani i zaštićeni tokom transporta',
    'services.page.transport.card3.title': 'Pratite Pošiljku',
    'services.page.transport.card3.desc': 'Real-time informacije o statusu vaše isporuke',
    'services.page.cta.title': 'Spremni za Saradnju?',
    'services.page.cta.desc': 'Kontaktirajte nas danas i saznajte više o našim proizvodima i uslugama. Naš tim je spreman da vam pomože u izboru najboljih rešenja za vaše potrebe.',
    'services.page.cta.button1': 'Pošaljite Upit',
    'services.page.cta.button2': 'Pozovite Nas',
    'contact.page.title': 'Kontaktirajte nas',
    'contact.page.subtitle': 'Pozovite nas ili pošaljite poruku - tu smo da odgovorimo na vaša pitanja',
    'contact.page.why_choose.title': 'Zašto izabrati nas?',
    'contact.page.why_choose.item1': 'Brza dostava širom Srbije',
    'contact.page.why_choose.item2': 'Kvalitetni proizvodi',
    'contact.page.why_choose.item3': 'Konkurentne cene',
    'contact.page.why_choose.item4': 'Profesionalna podrška',
  },
  en: {
    'nav.home': 'Home',
    'nav.services': 'Services',
    'nav.contact': 'Contact',
    'hero.heading': 'Paper Products',
    'hero.tagline': 'Easy hygiene with Lako Sistem',
    'hero.cta': 'Request a Quote',
    'about.title': 'About us',
    'about.text1': 'Lako Sistem is a leading company in the field of paper products and professional chemicals for hotels and catering facilities. With years of experience, we are dedicated to providing premium products and services.',
    'about.text2': 'Our slogan "Easy Hygiene with Lako Sistem" reflects our mission - to make hygiene maintenance simple and efficient for all our clients.',
    'about.card1.title': 'Years of Experience',
    'about.card1.desc': 'Reliable partner in hygiene and supplies',
    'about.card2.title': 'Premium Products',
    'about.card2.desc': 'Highest quality standards for your needs',
    'about.card3.title': 'Fast Delivery',
    'about.card3.desc': 'Efficient logistics throughout Serbia',
    'features.heading': 'Why Choose Lako Sistem?',
    'features.subheading': 'With years of experience in the industry, we provide premium products and services that meet the highest quality standards.',
    'features.feature1': 'High quality products',
    'features.feature2': 'Competitive prices',
    'features.feature3': 'Fast delivery',
    'features.feature4': 'Professional support',
    'features.feature5': 'Wide selection of products',
    'features.feature6': 'Years of experience',
    'features.cta.title': 'Request a Quote',
    'features.cta.desc': 'Contact us today and get a personalized quote tailored to your needs.',
    'features.cta.button': 'Contact Us',
    'features.quality.title': 'Premium Quality',
    'features.quality.desc': 'We work only with renowned manufacturers',
    'features.delivery.title': 'Fast Delivery',
    'features.delivery.desc': 'Reliable delivery throughout Serbia',
    'features.support.title': '24/7 Support',
    'features.support.desc': 'Always here when you need us',
    'features.price.title': 'Competitive Prices',
    'features.price.desc': 'Best price-quality ratio',
    'services.title': 'Our Services',
    'services.subtitle': 'Complete range of products and services for hygiene maintenance in your facility',
    'services.paper.title': 'Paper Products',
    'services.paper.desc': 'Wide range of paper products for all your needs - toilet paper, napkins, serviettes and much more.',
    'services.paper.button': 'Learn more',
    'services.paper.item1': 'Premium quality toilet paper',
    'services.paper.item2': 'Napkins and serviettes in various sizes',
    'services.paper.item3': 'Kitchen rolls and paper towels',
    'services.paper.item4': 'Specialized hotel products',
    'services.chemistry.title': 'Hotel Chemicals',
    'services.chemistry.desc': 'Professional chemicals for cleaning and maintenance of hotels, restaurants and business premises.',
    'services.chemistry.button': 'Learn more',
    'services.chemistry.item1': 'Detergents and washing agents',
    'services.chemistry.item2': 'Disinfectants',
    'services.chemistry.item3': 'Kitchen cleaning products',
    'services.transport.title': 'Transport and Delivery',
    'services.transport.desc': 'Fast and reliable delivery of your orders directly to your address.',
    'services.transport.button': 'Learn more',
    'contact.title': 'Contact us',
    'contact.subtitle': 'We are ready to answer all your questions and help with your needs',
    'contact.name': 'Full name',
    'contact.email': 'Email',
    'contact.phone': 'Phone',
    'contact.message': 'Message',
    'contact.send': 'Send message',
    'contact.sending': 'Sending...',
    'contact.success': 'Message sent successfully!',
    'contact.error': 'Error sending message. Please try again.',
    'contact.form.title': 'Send us a message',
    'contact.info.title': 'Contact Information',
    'contact.info.phone.label': 'Phone',
    'contact.info.phone.note': 'Always available',
    'contact.info.email.label': 'Email',
    'contact.info.email.note': 'We respond within 24h',
    'contact.info.address.label': 'Address',
    'contact.info.address.note': 'Visits by appointment only',
    'contact.info.address': 'Bulevar Oslobodjenja 133a/3, 11000 Belgrade',
    'contact.info.phone': '+381 60 66 77 009',
    'contact.info.email': 'lakosistem@aislike.rs',
    'footer.quick_links': 'Quick Links',
    'footer.contact_info': 'Contact Information',
    'footer.tagline': 'Easy Hygiene with Lako Sistem',
    'footer.description': 'Your reliable partner for professional hygiene products and services.',
    'footer.rights': '© 2024 Lako Sistem. All rights reserved.',
    'services.page.title': 'Our Services and Transport',
    'services.page.subtitle': 'Paper products and professional cleaning chemicals in large quantities, with delivery and transport to your door',
    'services.page.paper.title': 'Paper Products',
    'services.page.paper.desc': 'We offer a complete range of paper products for hotels, restaurants and catering facilities. Our products are characterized by high quality and affordable prices.',
    'services.page.paper.why': 'Why Choose Us',
    'services.page.chemistry.references': 'Our References',
    'services.page.chemistry.ref_text1': 'We work with leading hotel chains, restaurants and business facilities in the region. Our clients recognize the quality of our program and reliability in delivery. Whether you run a boutique hotel, a large hotel chain or a restaurant chain, we have a solution for you.',
    'services.page.chemistry.ref_text2': 'All products are tested and approved by relevant institutions, guaranteeing you the highest standards of hygiene and safety for your guests and employees.',
    'services.page.paper.products': 'Our products:',
    'services.page.paper.p1': 'Toilet paper (1-4 layers)',
    'services.page.paper.p2': 'Napkins and serviettes in various sizes',
    'services.page.paper.p3': 'Kitchen rolls',
    'services.page.paper.p4': 'Paper towels',
    'services.page.paper.p5': 'Industrial rolls',
    'services.page.chemistry.title': 'Professional Chemicals',
    'services.page.chemistry.desc': 'Professional cleaning chemicals that guarantee the highest hygiene standards. All products are certified and safe to use.',
    'services.page.chemistry.products': 'Our offer:',
    'services.page.chemistry.p1': 'Detergents and softeners',
    'services.page.chemistry.p2': 'Disinfectants',
    'services.page.chemistry.p3': 'Glass cleaning products',
    'services.page.chemistry.p4': 'Kitchen cleaning products',
    'services.page.chemistry.p5': 'Bathroom cleaning products',
    'services.page.chemistry.p6': 'Floor cleaning products',
    'services.page.transport.title': 'Transport and Delivery',
    'services.page.transport.desc': 'We provide fast and reliable delivery throughout Serbia. Our fleet enables product transport in optimal conditions.',
    'services.page.transport.features': 'Benefits of our transport:',
    'services.page.transport.f1': 'Free delivery for orders over a certain value',
    'services.page.transport.f2': 'Flexible delivery schedules',
    'services.page.transport.f3': 'Professional drivers',
    'services.page.transport.f4': 'Real-time shipment tracking',
    'services.page.transport.f5': 'Safe and fast delivery',
    'services.page.transport.card1.title': 'Fast Delivery',
    'services.page.transport.card1.desc': 'Delivery within 24-48h throughout Serbia',
    'services.page.transport.card2.title': 'Secure Packaging',
    'services.page.transport.card2.desc': 'Products carefully packed and protected during transport',
    'services.page.transport.card3.title': 'Track Shipment',
    'services.page.transport.card3.desc': 'Real-time information about your delivery status',
    'services.page.cta.title': 'Ready to Collaborate?',
    'services.page.cta.desc': 'Contact us today and learn more about our products and services. Our team is ready to help you choose the best solutions for your needs.',
    'services.page.cta.button1': 'Send Inquiry',
    'services.page.cta.button2': 'Call Us',
    'contact.page.title': 'Contact us',
    'contact.page.subtitle': 'Call us or send a message - we are here to answer your questions',
    'contact.page.why_choose.title': 'Why choose us?',
    'contact.page.why_choose.item1': 'Fast delivery throughout Serbia',
    'contact.page.why_choose.item2': 'Quality products',
    'contact.page.why_choose.item3': 'Competitive prices',
    'contact.page.why_choose.item4': 'Professional support',
  },
};
